apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: stocktrack
type: Opaque
stringData:
  DB_PASSWORD: "mypassword"
  ALPHAVANTAGE_STOCK_API_KEY: "ST3RQRPRZLT30Y2C"
  ALPHAVANTAGE_NEWS_API_KEY: "W4IRJN9I3GOQN52O"
